name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Python Base Image
        run: |
          docker build -t lambda_base_python -f docker/base_python.Dockerfile .

      - name: Build Node Base Image
        run: |
          docker build -t lambda_base_node -f docker/base_node.Dockerfile .

      - name: Run Python Unit Tests
        run: |
          PYTHONPATH=$PYTHONPATH:. pytest backend/tests/

      - name: Run JavaScript Tests (if any)
        run: |
          if [ -f "package.json" ]; then
            npm install
            npm test
          fi

      - name: Lint Python Code
        run: |
          flake8 backend/ --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 backend/ --count --exit-zero --max-complexity=10 --statistics