name: Simple CI/CD

on:
  push:
    branches: [ main, Aryans_Branch ]
  pull_request:
    branches: [ main, Aryans_Branch ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest httpx
    
    - name: Run tests
      run: |
        PYTHONPATH=$PYTHONPATH:$(pwd) pytest backend/tests/
    
    - name: Check code style
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics 