name: Simple CI/CD

on:
  push:
    branches: [ main, Aryans_Branch ]
  pull_request:
    branches: [ main, Aryans_Branch ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    
    - name: Run tests
      run: |
        pytest backend/tests/
    
    - name: Check code style
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Python base image
      uses: docker/build-push-action@v2
      with:
        context: ./docker
        file: ./docker/Dockerfile.python
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/lambda_base_python:latest
    
    - name: Build and push Node.js base image
      uses: docker/build-push-action@v2
      with:
        context: ./docker
        file: ./docker/Dockerfile.node
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/lambda_base_node:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Deploy to staging
      run: |
        # Add your deployment commands here
        echo "Deploying to staging..."
    
    - name: Run integration tests
      run: |
        # Add your integration test commands here
        echo "Running integration tests..."
    
    - name: Deploy to production
      if: success()
      run: |
        # Add your production deployment commands here
        echo "Deploying to production..." 